baseURL = "https://mohdsahlpa.github.io/"
title = "sahl"
theme = "PaperMod"
languageCode = "en-us"
enableInlineShortcodes = true

[params]
  author = "mohdsahlpa"
  description = "CS Student | Developer | Hacker | Learner"
  ShowBreadCrumbs = true
  ShowReadingTime = true

[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 1
